Repository dylarcher/nodeman-cli, pull requests merged in 2025-05, with the labels that each got.

#23 Create label.yml
  .github/workflows/label.yml
Labels: config

#24 Create codeql.yml
  .github/.workflows/actions.yml
  .github/.workflows/changes.yml
  .github/.workflows/feedback.yml
  .github/.workflows/formats.yml
  .github/.workflows/includes.yml
  .github/.workflows/linter.yml
  .github/.workflows/security.yml
  .github/.workflows/static.yml
  .github/.workflows/summarize.yml
  .github/.workflows/update.yml
  .github/.workflows/validate.yml
  .github/.workflows/version.yml
  .github/workflows/codeql.yml
  docs/repository-open-graph-template.png
Labels: automation, config

#30 Create label.yml
  .github/labeler.yml
  .github/workflows/label.yml
Labels: automation, config

#29 point to demo from package source
  package.json
Labels: automation, config

#48 Feature/templates
  .github/ISSUE_TEMPLATE/config.yml
  .vscode/settings.json
Labels: chore
